# Generated by Django 4.0.4 on 2022-04-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned_by', models.CharField(max_length=180)),
                ('status', models.CharField(default='disabled', max_length=8)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
