# Generated by Django 4.0.4 on 2022-04-27 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_wallet_owned_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposited_by', models.CharField(max_length=180)),
                ('status', models.CharField(max_length=8, null=True)),
                ('deposited_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('reference_id', models.CharField(max_length=180, unique=True)),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wallet')),
            ],
        ),
    ]
